# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 63063696bb2f31cf9fec79e7bb0be22a817b86bb6148bbfca106321c12bf288e732e4e1a168495b7960d693878faace16413c1941edada8cd68679590ef9d499

test:
  secret_key_base: 3e5361495cd72308042eedf6c33b609af75ff6a8e5e7bc1734e023a1b58533aef993e13eae5a9b876f9d7e62d35ab379894af266df184b64176cad0cdbe12abd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
